# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sent_emails',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Counts how many time an email is sent to this address.'),
        ),
    ]
